OOPCourse/src/objects/Candidate__c.object
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

OOPCourse/src/objects/Job_Application__c.object
<CustomObject>
    <fields>
        <fullName>Candidate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Candidate</label>
        <referenceTo>Candidate__c</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job Application</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

OOPCourse/src/classes/JobAppManager.cls
public with sharing class JobAppManager {
    
    //TODO: This is the method to create a job application for a candidate
    public void createJobAppForCandidate(List<Candidate__c> candidateForJobApp){
        
        //TODO: Declare a new List named newJobApplicationList. The type of the list is Job_Application__c.
        List<Job_Application__c> newJobApplicationList = new List<Job_Application__c>();
        //TODO: Create a loop to iterate over all of the values in candidateForJobApp...
        //... Name the iteration variable candidate.
        ////TODO: Declare a new Job Application named newJobApplication.
        ////TODO: Assign the ID of the loop iteration variable, candidate,****** 
        ////to the Candidate__c field of newJobApplication
        ////TODO: Add newJobApplication to newJobApplicationList
        for(Candidate__c candidate : candidateForJobApp){
            Job_Application__c newJobApplication = new Job_Application__c();  
            //newJobApplication.candidate = candidateForJobApp.id  this is how I first did it.*****
            newJobApplication.Candidate__c = candidate.Id;
            newJobApplicationList.add(newJobApplication);
        }
        insert newJobApplicationList;
        
    }
}