OOPCourse/src/objects/Candidate__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

OOPCourse/src/objects/Job_Application__c.object
<CustomObject>
    <fields>
        <fullName>Candidate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Candidate</label>
        <referenceTo>Candidate__c</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job Application</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

OOPCourse/src/objects/Offer__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Salary__c</fullName>
        <label>Actual Salary</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Job_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job Application</label>
        <referenceTo>Job_Application__c</referenceTo>
        <relationshipLabel>Offers</relationshipLabel>
        <relationshipName>Offers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Offer_Date__c</fullName>
        <label>Offer Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Offer_Expiration_Date__c</fullName>
        <label>Offer Expiration Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Offer</label>
    <nameField>
        <displayFormat>OFF-{0000}</displayFormat>
        <label>Offer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

OOPCourse/src/classes/OfferGenerator.cls
public with sharing class OfferGenerator {




public void createCandidate(string firstName, string lastName){ 

        Candidate__c newCandidate = new Candidate__c(); 

        newCandidate.First_Name__c = firstName; 

        newCandidate.Last_Name__c = lastName;        

        insert newCandidate;       

        createJobApplication(newCandidate.Id);

}




public void createJobApplication(ID candidateForJobAppId){ 

        Job_Application__c jobApp = new Job_Application__c();       

        jobApp.Candidate__c = candidateForJobAppId; 

        insert jobApp;        

        createOffer(jobApp.Id);

    }



public void createOffer(ID jobAppForOfferId){

Offer__c newOffer = new Offer__c();

newOffer.Offer_Date__c = Date.today(); 

newOffer.Offer_Expiration_Date__c = Date.today().addMonths(1); 

newOffer.Actual_Salary__c = 60000;

newOffer.Status__c ='Sent';        

newOffer.Job_Application__c = jobAppForOfferId; 

insert newOffer;        

        System.debug('New Offer Id: ' + newOffer.Id);

}

}