OOPCourse/src/objects/Candidate__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Years_of_Experience__c</fullName>
        <label>Years of Experience</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

OOPCourse/src/classes/CandidateExperience.cls
public with sharing class CandidateExperience {

    public void getCandidatesWithExperience(Integer yearsExperience){
        
        List<Candidate__c> experiencedCandidates = [SELECT Name, Id, Last_Name__c, First_Name__c, Email__c, Years_of_Experience__c 
                                                    FROM Candidate__c
                                                    WHERE Years_of_Experience__c >= : yearsExperience];
        
        for(Candidate__c cand : experiencedCandidates){
            System.debug(cand.First_Name__c + ' ' + cand.Last_Name__c);
            System.debug(cand.Email__c);
            System.debug('Experience: ' + cand.Years_of_Experience__c + ' years');
        }        
    }
}