OOPCourse/src/objects/Candidate__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

OOPCourse/src/objects/Job_Application__c.object
<CustomObject>
    <fields>
        <fullName>Candidate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Candidate</label>
        <referenceTo>Candidate__c</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job Application</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

OOPCourse/src/objects/Offer__c.object
<CustomObject>
    <fields>
        <fullName>Job_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job Application</label>
        <referenceTo>Job_Application__c</referenceTo>
        <relationshipLabel>Offers</relationshipLabel>
        <relationshipName>Offers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Offer</label>
    <nameField>
        <displayFormat>OFF-{0000}</displayFormat>
        <label>Offer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

OOPCourse/src/classes/OfferGenerator_Test.cls
@isTest
private class OfferGenerator_Test {
    
    @testSetup
    private static void createTestData(){
        OfferGenerator og = new OfferGenerator();
        og.createCandidate('Test', 'Candidate');
    }
    
    private static testMethod void testCandidate(){   	
        
        Candidate__c testCandidate = [SELECT Id FROM Candidate__c WHERE First_Name__c = 'Test' AND Last_Name__c = 'Candidate' LIMIT 1];
        
        System.assert(testCandidate != null);
        
        Job_Application__c testJobApplication = [SELECT Id FROM Job_Application__c WHERE Candidate__c =: testCandidate.Id LIMIT 1];
        
        System.assert(testJobApplication != null);
        
        Offer__c testOffer = [SELECT Id FROM Offer__c LIMIT 1];
        
        System.assert(testOffer != null);
    }
}